name: Build Android APK

on:
  workflow_dispatch: # 手动触发
  push:
    branches:
      - main # 你可以改成你要触发的分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 安装 Java（Android 构建需要 Java）
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. 安装 Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0' # 可改为你本地用的版本

      # 4. 获取依赖
      - name: Install dependencies
        run: flutter pub get
        working-directory: simple_live_app

      # 5. 构建 APK（分架构）
      - name: Build APK
        run: flutter build apk --split-per-abi
        working-directory: simple_live_app

      # 6. 上传构建产物到 GitHub Actions
      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: simple_live_app/build/app/outputs/flutter-apk/*.apk
